src/Entity/Movie.php
<?php


namespace App\Entity;


class Movie
{
    /**
     * @var int
     */
    private $id;
    /**
     * @var string
     */
    private $poster;
    /**
     * @var string
     */
    private $title;

    public function __construct(int $id, string $poster, string $title)
    {
        $this->id = $id;
        $this->poster = $poster;
        $this->title = $title;
    }

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getMediumPoster(): string
    {
        return 'https://image.tmdb.org/t/p/w342/'.$this->poster;
    }

    /**
     * @return string
     */
    public function getLargePoster(): string
    {
        return 'https://image.tmdb.org/t/p/w500/'.$this->poster;
    }

    /**
     * @return string
     */
    public function getTitle(): string
    {
        return $this->title;
    }
}

src/Entity/MovieDetails.php
<?php


namespace App\Entity;


class MovieDetails
{
    private $movie;
    private $overview;
    private $releaseDate;
    private $voteAverage;
    private $duration;

    public function __construct(Movie $movie, string $overview, \DateTimeInterface $releaseDate, float $voteAverage, int $duration)
    {
        $this->movie = $movie;
        $this->overview = $overview;
        $this->releaseDate = $releaseDate;
        $this->voteAverage = $voteAverage;
        $this->duration = $duration;
    }

    /**
     * @return Movie
     */
    public function getMovie(): Movie
    {
        return $this->movie;
    }

    /**
     * @return string
     */
    public function getOverview(): string
    {
        return $this->overview;
    }

    /**
     * @return \DateTimeInterface
     */
    public function getReleaseDate(): \DateTimeInterface
    {
        return $this->releaseDate;
    }

    /**
     * @return float
     */
    public function getVoteAverage(): float
    {
        return $this->voteAverage;
    }

    /**
     * @return int
     */
    public function getDuration(): int
    {
        return $this->duration;
    }
}

src/Controller/DefaultController.php
<?php


namespace App\Controller;

use App\Api\MovieApiInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;

class DefaultController extends AbstractController
{
    /**
     * @Route("/", name="homepage")
     */
    public function index(MovieApiInterface $movieApi)
    {
        $movies = $movieApi->findTopMovies();

        return $this->render('index.html.twig', ['movies' => $movies]);
    }

    /**
     * @Route("/{id}", name="details")
     */
    public function details(string $id, MovieApiInterface $movieApi)
    {
        $details = $movieApi->getMovieDetailsById($id);
        if (!$details) {
            throw new NotFoundHttpException();
        }

        return $this->render('details.html.twig', ['details' => $details]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Pop movies{% endblock %}</title>
    <link href="//cdn.muicss.com/mui-0.9.41/css/mui.min.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/css/style.css?v=1.5" rel="stylesheet" type="text/css"/>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

</head>
{% block stylesheets %}{% endblock %}
</head>
<body>
<div id="content-wrapper">
    <div class="mui-appbar">

        <table width="100%">
            <tr style="vertical-align:middle;">
                <td class="mui--appbar-height" style="padding-left: 15px">{% block appbar_action %}{% endblock %}</td>
            </tr>
        </table>
    </div>

    {% block body %}{% endblock %}
</div>
{% block javascripts %}{% endblock %}
</body>
</html>

templates/details.html.twig
{% extends 'base.html.twig' %}
{% block appbar_action %}
    <a href="{{ path('homepage') }}"><i class="go-back fas fa-arrow-left"></i></a><h1 style="">Movie Details</h1>
{% endblock %}
{% block body %}
    <div class="detail">
        <div class="detail__header">
            <h2>{{ details.movie.title }}</h2>
        </div>
        <div class="detail__block">
            <div class="detail__block-img">
                <img src="{{ details.movie.mediumPoster }}"/>
            </div>
            <div class="detail__block-content">
                <p class="detail__block--big-gray-text">{{ details.releaseDate|date('Y') }}</p>
                <p class="detail__block--big-gray-text"><i>{{ details.duration }} min</i></p>
                <p class="detail__block-rating">{{ details.voteAverage }}/10</p>
            </div>
        </div>
        <div class="detail__description">
            <p>{{ details.overview }}</p>
        </div>
    </div>
{% endblock %}

templates/index.html.twig
{% extends 'base.html.twig' %}
{% block appbar_action %}
    <h1>Pop Movies</h1>
{% endblock %}
{% block body %}

    <div class="mui-row">
        {% for movie in movies %}
            <div class="mui-col-xs-6">
                <a href="{{ path('details', {id: movie.id}) }}">
                    <img src="{{ movie.largePoster }}" style="max-width: 100%;"/></a>
            </div>
        {% endfor %}
    </div>

{% endblock %}